### ISSUE TITLE
SW: RTC and timezones

### ISSUE THREAD

**Issue by ppannuto** [lab11/socitrack#17]
I spent a minute trying to figure out how one of my nodes had gotten three hours off today, only to eventually put together that it was indeed 10:20 US/Pacific... I'm not sure what exactly the best policy is here, but I think it makes sense to program the RTC on the board with UTC time as programming the RTC is ideally rare and could happen anywhere, so that should be globally consistent.

We should probably add something to the data processing as well, but I think "which time zone was this device in while recording" is more of a metadata problem.

**Comment by hedgecrw** [comment]
This has been resolved with the latest check-in.
