### ISSUE TITLE
SW: Rev M — Updated connection information (since rev L)

### ISSUE THREAD

**Issue by ppannuto** [lab11/socitrack#47]
There is no more `LED2`, there is only `LED1_{RED,GREEN}`. The `LED1` pins are unchanged.

DWM1:
 - `!SPI_CS` — `GP29` (same)
 - `!RST` — `GP50` (same)
 - `WAKEUP` — `GP26` (same)
 - `IRQ` — `GP27` (same)

DWM2:
 - `!SPI_CS` — `GP24` (same)
 - `!RST` — `GP82` **!! This pin is also `SWTRACE2` on the AP4BP module.***
 - `WAKEUP` — `GP63`
 - `IRQ` — `GP72`

DWM3:
 - `!SPI_CS` — `GP25` (same)
 - `!RST` — `GP83` **!! This pin is also `SWTRACE3` on the AP4BP module.***
 - `WAKEUP` — `GP88`
 - `IRQ` — `GP76`

*We aren't using the SWTRACE, and I ran out of GPIOs I could reasonably escape from the BGA, so I reused these two. If we do ever enable SWTRACE to debug something, need to remove `RZ2` and `RZ3` to avoid resetting DWM2 and DWM3 all the time [can use empty `RX2` and `RX3` pads to tie them to the DWM1 `!RST`]

**Comment by hedgecrw** [comment]
Done.
