### ISSUE TITLE
SW: Pin reconfigurations for Rev G

### ISSUE THREAD

**Issue by ppannuto** [lab11/socitrack#8]
Some of the pins for the nrf updated from Rev F to Rev G. I tried to make sure that nothing _bad_ would happen if old rev software runs, but the one risk is the `BUZZER_GATE`, which is floating and might burn out the speaker if not pulled off. That was an unconnected pin before, so it's safe to change that in the Rev F firmware as well such that the speaker is simply always controlled.

**Revision G:**
<img width="720" alt="image" src="https://user-images.githubusercontent.com/339422/86535766-b9dcd380-beb0-11ea-9b27-6445b6efea01.png">

**Revision F:**
<img width="649" alt="image" src="https://user-images.githubusercontent.com/339422/86536074-c5c99500-beb2-11ea-964d-ca6ece3084d8.png">

---

## Changed Pin List

(You should probably double-check me, just in case :) )

 - [x] USB pins now connected
 - [x] `LED_NRF_GREEN` `P0.06` -> `P1.05`
 - [x] `DBG_RX` removed (was FTDI UART)
 - [x] `DBG_TX` removed (was FTDI UART)
 - [x] `!SD_DETECT` `P1.00` -> `P0.11`
 - [x] `LED_NRF_BLUE` `P0.04` -> `P1.07`
 - [x] `LED_NRF_RED` `P0.05` -> `P1.04`
 - [x] (new) `!CHG` `P1.02` -- "Low (FET on) indicates charging and OpenDrain (FET off) indicates no Charging or Charge complete."
 - [x] (new) `!PG` `PXXX` -- "Low (FET on) indicates the input voltage is above UVLO and the OUT (battery) voltage."
    - From https://www.ti.com/lit/ds/symlink/bq24040.pdf?ts=1593963502813&ref_url=https%253A%252F%252Fwww.ti.com%252Fproduct%252FBQ24040
 - [x] `!FT_RST` removed (was FTDI reset signal)
 - [x] (new) `BUZZER_GATE` `P1.15` -- Drives a PFET that drives a buzzer. **Must be pulled high to default buzzer off.** This was intentionally put on an unconnected pin in prior revisions, so all firmware should drive this pin to ensure it isn't accidentally floated. Should be driven with a PWM signal to drive buzzer.
 - [x] (new) `QI_TS_CTRL` `P0.25` -- `TS/CTRL` pin of [bq51013B](https://www.ti.com/lit/ds/symlink/bq51013b.pdf?HQS=TI-null-null-digikeymode-df-pf-null-wwe&ts=1593963941247), see §7.3.14 for details. Used to signal charge complete to wireless charger.

**Comment by ppannuto** [comment]
Buzzer details:

<img width="254" alt="image" src="https://user-images.githubusercontent.com/339422/86536511-3920d600-beb6-11ea-9dad-00856ac8e496.png">

http://www.puiaudio.com/pdf/SMT-0440-T-2-R.pdf

**Comment by hedgecrw** [comment]
All changes implemented with latest push
